name: gotzmann_app
description: Offizielle Gotzmann App – Portfolio, Workshops, Buchungsanfragen
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
    - assets/content/
