name: gotzmann_app
description: Offizielle Gotzmann App – Portfolio, Workshops, Buchungsanfragen
version: 0.1.0+1
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  flutter_markdown: ^0.6.18
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  webview_flutter: ^4.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
    - assets/content/
