name: Flutter CI (minimal green)

on:
  push:
    branches: [ main, bootstrap/api-only-ci ]
  pull_request:
    branches: [ main, bootstrap/api-only-ci ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          # Optional: falls du pinnen willst
          # flutter-version: "3.22.2"

      - name: Versions
        run: |
          flutter --version
          dart --version

      - name: Pub get
        run: flutter pub get
